### ISSUE TITLE
Coinflip bot game

### ISSUE THREAD

**Issue by Le-SirH** [TheTypingMatch/le-cash-bot#15]
Currently, there is 1 bot game available for a chance to earn extra cash for LeCashBot and that is the [`$bet`](https://github.com/TheTypingMatch/le-cash-bot/blob/master/src/commands/bet.js) command. Previously, the bot featured a `$coinflip` command as well but it was basically the [`$bet`](https://github.com/TheTypingMatch/le-cash-bot/blob/master/src/commands/bet.js) command but with a constant chance of 50% to win.

This coinflip game should be similarly structured to the [`$daily`](https://github.com/TheTypingMatch/le-cash-bot/blob/master/src/commands/daily.js) command; a win streak rewards users starting at a $100 reward and doubling for every streak win. 

For example, the coinflip data may be stored like this:
```js
coinflip: {
    type: Object, 
    required: false, 
    default: {
        currentStreak: 0, 
        highestStreak: 0
    }
},
```
...and rewards may be decided similar to the following:
```js
// f(x) = 100 * 2^(x-1)
const reward = 100 * (2 ** (streak - 1))
```

Streaks may also be displayed on user [profiles](https://github.com/TheTypingMatch/le-cash-bot/blob/master/src/commands/profile.js) as well. Additionally, there may be a leaderboard for the highest win streaks.

**Comment by TheProdigyHenry** [comment]
Will the user be betting any cash, or does it automatically start at $100? Basically, do you need to spend money at all to get money or is it just a free money command?

**Comment by Le-SirH** [comment]
Good question. I think I might make a cost of $100 for every coinflip command to begin with. 

| Streak | Profit | Winnings |
|---|---|---|
| 1 | $0 | $100 |
| 2 | $100 | $200 |
| 3 | $300 | $400 |
| 4 | $700 | $800 |
| ... | ... | ... |

What do you think @TheProdigyHenry?

**Comment by TheProdigyHenry** [comment]
Sounds good.

**Comment by Le-SirH** [comment]
I'm going to have to make a `$leaderboard coinflip` command argument and a current streak displayed on profiles as well.

**Comment by Le-SirH** [comment]
@TheProdigyHenry 2 things:

1. What do you think should be the cool down for the `$coinflip` command?
2. I have the command working but it seems to be very *underwhelming* and not rewarding enough for a high streak. Even a streak of 4 is a high streak because the chances are 6.25% but the reward is only $800. Any suggestions?

**Comment by TheProdigyHenry** [comment]
@Le-SirH 

1. I don't know if this is possible but 3-10 seconds between streaks. After a streak ends, 30-60 seconds to use the command again and begin a new streak.
2. Perhaps instead of starting with 2 as a base, start with another number like "e". For a streak of 4, the formula e^(n-1) gives $2,009 which is kind of more appealing. You can increase the base as necessary, but keep in mind that the higher the base, is the more cash people can win. Another idea would be to increase the multiplier: 100x * 2^(n-1), where "x" increases every streak or so.

I'd let you know if I come up with any more ideas.

**Comment by Le-SirH** [comment]
That sounds more like it.

**Comment by Le-SirH** [comment]
The bet chances are determined by the cash amount. Maybe I could use the inverse function of that to determine the reward based on the chance of such a streak.

**Comment by Le-SirH** [comment]
### To Do
1. Modify winnings/cost for command.
2. Display cost to use the command and the cost if users were to use the command a second time.
3. Display highest streak on user profiles.
4. Coinflip leaderboard.

**Comment by Le-SirH** [comment]
Possible new `$coinflip` rewards:

winnings:  `100 * (3 ^ (streak - 1)) + (streak * 150)`
cost:      `100 * (2 ^ streak)`

| streak | winnings   | cost    | total profit | chances |
| ---    | ---        | ---     | ---          | ---     |
| 0      | $33        | $100    | $-67         | 50%     |
| 1      | $100       | $200    | $50          | 25%     |
| 2      | $300       | $400    | $200         | 12.5%   |
| 3      | $900       | $800    | $550         | 6.25%   |
| 4      | $2,700     | $1,600  | $1,700       | 3.12%   |
| 5      | $8,100     | $3,200  | $5,650       | 1.56‬%   |
| 6      | $24,300    | $4,800  | $18,800      | 0.78%   |
| 7      | $72,900    | $9,200  | $61,150      | 0.39%   |
| 8      | $218,700   | $16,400 | $194,300     | 0.19‬%   |
| 9      | $656,100   | $32,800 | $606,250     | 0.09‬%   |
| 10     | $1,968,300‬ | $49,600 | $1,867,400   | 0.04%   |
| ...    | ...        | ...     | ...          | ...     |

@TheProdigyHenry Any suggestions or do you think this is good?
