### ISSUE TITLE
LeCashBot triggers every time a message begins with "$".

### ISSUE THREAD

**Issue by TheProdigyHenry** [TheTypingMatch/le-cash-bot#2]
Every time a message begins with the symbol "$", LeCashBot is triggered into saying "That command doesn't exist!" regardless of whether it is a command or not. This is getting annoying. Perhaps you can remove this feature altogether. If a command doesn't exist, the bot does not respond at all.

**Comment by Le-SirH** [comment]
Thank you for the feedback, Henry. That sounds like a good idea.
