### ISSUE TITLE
Discord.js v12 is incompatible with Node.js v10

### ISSUE THREAD

**Issue by Le-SirH** [TheTypingMatch/le-cash-bot#33]
LeCashBot runs on a Debian 8 server. With the new Discord.js v12 update, Debian 8 seems to be incompatible with the new version. I believe Discord.js v11 requires NodeJS v6.0.0 or higher but Discord.js v12 requires NodeJS v12.0.0 or higher. The highest version Debian 8 seems to support is NodeJS v10. Any suggestions on solutions?

**Comment by iwa** [comment]
https://github.com/nodesource/distributions/blob/master/README.md#debinstall

but you really should migrate to Debian 10 as Debian 8 is on end-of-life *(LTS support will stop in around a month)*
like that you won't have any problems of compatibility

**Comment by Le-SirH** [comment]
Sounds good.

**Comment by iwa** [comment]
which hosting service do you use for your server, if i may ask ?

**Comment by Le-SirH** [comment]
I self-host it. I'm considering switching to a hosting service, though.

**Comment by iwa** [comment]
well self-hosting is good too as long as you can be sure that your server can run 24/7

**Comment by Le-SirH** [comment]
Indeed.

**Comment by Le-SirH** [comment]
This has been fixed with the [implementation of TypeScript](https://github.com/TheTypingMatch/le-cash-bot/issues/40).
