### ISSUE TITLE
$help command categories

### ISSUE THREAD

**Issue by Le-SirH** [TheTypingMatch/le-cash-bot#34]
As more commands are created, the help command description is getting too large. It can be split into the following categories:
- Register
- Guides
- Economy
- Games
- Misc.

![](https://cdn.discordapp.com/attachments/689251634244616290/709013919670337586/unknown.png)

**Comment by Le-SirH** [comment]
Alright all of this is done. All I need left is a small function that capitalized the category name..

**Comment by DamienVesper** [comment]
```
String.replace(/^\w/, f => f.toUpperCase())
```
